HGCal Test Beam: HGCalElectronicsMap Class Reference
HGCalElectronicsMap Class Reference
#include <HGCalElectronicsMap.h>
Classes
struct MapEntry
Public Member Functions
bool existsDetId (DetId did) const
bool existsEId (uint32_t eid) const
DetId eid2detId (uint32_t eid) const
uint32_t detId2eid (DetId did) const
void insert (uint32_t, DetId did)
size_t size () const
uint32_t eidAt (size_t i) const
DetId didAt (size_t i) const
Detailed Description
Date:
Revision:
Author
J. Mans - Minnesota
Member Function Documentation
uint32_t HGCalElectronicsMap::detId2eid (DetId did) const
DetId HGCalElectronicsMap::didAt (size_t i) const
Referenced by HGCalCondObjectTextIO::store().
DetId HGCalElectronicsMap::eid2detId (uint32_t eid) const
References HGCalElectronicsMap::MapEntry::eid.
uint32_t HGCalElectronicsMap::eidAt (size_t i) const
Referenced by HGCalCondObjectTextIO::store().
bool HGCalElectronicsMap::existsDetId (DetId did) const
bool HGCalElectronicsMap::existsEId (uint32_t eid) const
References HGCalElectronicsMap::MapEntry::eid.
void HGCalElectronicsMap::insert (uint32_t eid, DetId did)
References HGCalElectronicsMap::MapEntry::detid, and HGCalElectronicsMap::MapEntry::eid.
Referenced by HGCalCondObjectTextIO::load().
size_t HGCalElectronicsMap::size () const inline
Referenced by HGCalCondObjectTextIO::store().
The documentation for this class was generated from the following files:
CondObjects/interface/HGCalElectronicsMap.h
CondObjects/src/HGCalElectronicsMap.cc