HGCal Test Beam: HGCCellMap Class Reference
HGCCellMap Class Reference
#include <HGCCellMap.h>
Classes
struct Cell
Public Member Functions
HGCCellMap (std::string inputFilename="")
virtual ~HGCCellMap ()
std::pair< int, int > operator() (size_t cellid)
std::pair< double, double > operator() (std::pair< int, int > &uv)
std::pair< double, double > uv2xy (int u, int v)
std::pair< int, int > xy2uv (double x, double y)
int posid (int u, int v)
std::pair< int, int > uv2eid (int layer, int sensor_u, int sensor_v, int u, int v)
int celltype (int layer, int sensor_u, int sensor_v, int u, int v)
std::vector< HGCCellMap::Cell > cells (int layer=1, int sensor_u=0, int sensor_v=0)
TH2Poly * honeycomb ()
Detailed Description
Definition at line 17 of file HGCCellMap.h.
Constructor & Destructor Documentation
HGCCellMap::HGCCellMap (std::string inputFilename = "")
Definition at line 26 of file HGCCellMap.cc.
References HGCCellMap::Cell::celltype, celltype(), HGCCellMap::Cell::channel, HGCCellMap::Cell::count, HGCCellMap::Cell::posid, posid(), HGCCellMap::Cell::skiroc, HGCCellMap::Cell::u, HGCCellMap::Cell::v, HGCCellMap::Cell::x, HGCCellMap::Cell::y, and HGCCellMap::Cell::z.
HGCCellMap::~HGCCellMap () virtual
Definition at line 102 of file HGCCellMap.cc.
Member Function Documentation
std::vector< HGCCellMap::Cell > HGCCellMap::cells (int layer = 1, int sensor_u = 0, int sensor_v = 0)
Definition at line 107 of file HGCCellMap.cc.
int HGCCellMap::celltype (int layer, int sensor_u, int sensor_v, int u, int v)
Definition at line 163 of file HGCCellMap.cc.
Referenced by HGCCellMap().
TH2Poly* HGCCellMap::honeycomb () inline
Definition at line 60 of file HGCCellMap.h.
pair< int, int > HGCCellMap::operator() (size_t cellid)
Definition at line 119 of file HGCCellMap.cc.
std::pair<double, double> HGCCellMap::operator() (std::pair< int, int > & uv)
int HGCCellMap::posid (int u, int v)
Definition at line 174 of file HGCCellMap.cc.
Referenced by HGCCellMap().
pair< int, int > HGCCellMap::uv2eid (int layer, int sensor_u, int sensor_v, int u, int v)
Definition at line 145 of file HGCCellMap.cc.
pair< double, double > HGCCellMap::uv2xy (int u, int v)
Definition at line 135 of file HGCCellMap.cc.
pair< int, int > HGCCellMap::xy2uv (double x, double y)
Definition at line 156 of file HGCCellMap.cc.
The documentation for this class was generated from the following files:
TBStandaloneSimulator/interface/HGCCellMap.h
TBStandaloneSimulator/src/HGCCellMap.cc