HGCal Test Beam: HGCalTBRecHitProducer Class Reference
HGCalTBRecHitProducer Class Reference
#include <HGCalTBRecHitProducer.h>
Public Member Functions
HGCalTBRecHitProducer (const edm::ParameterSet &)
virtual void produce (edm::Event &, const edm::EventSetup &)
Detailed Description
Definition at line 32 of file HGCalTBRecHitProducer.h.
Constructor & Destructor Documentation
HGCalTBRecHitProducer::HGCalTBRecHitProducer (const edm::ParameterSet & cfg)
Definition at line 3 of file HGCalTBRecHitProducer.cc.
Member Function Documentation
void HGCalTBRecHitProducer::produce (edm::Event & event, const edm::EventSetup & iSetup) virtual
Todo:
check if reading the conditions from file some channels are not in the file!
Todo:
use time calibration!
Todo:
define an algorithm for the energy if more than 1 sample, code inefficient
Definition at line 11 of file HGCalTBRecHitProducer.cc.
References SKIROC2DataFrame::detid(), HGCalCondObjectContainer< Payload >::get(), HGCalCondObjectTextIO::load(), SKIROC2DataFrame::samples(), and HGCalTBNumberingScheme::scheme().
The documentation for this class was generated from the following files:
Reco/plugins/HGCalTBRecHitProducer.h
Reco/plugins/HGCalTBRecHitProducer.cc