HGCal Test Beam: Connection Class Reference
Connection Class Reference
#include <Connection.h>
Public Member Functions
Connection (TQObject *sender, const char *signal, PyObject *receiver, const char *method)
~Connection ()
bool noArgs (std::string &signal)
True if signal has no arguments.
TQObject * sender () const
const char * signal () const
PyObject * receiver () const
const char * method () const
Detailed Description
Model a signal/slot association. Many computing systems use the signal/slot model for associating a signal, for example a user interaction with a graphical user interface (GUI), and a slot, that is, a procedure or function that is executed in response to the signal. This class is designed to be used with Python. See TheNtupleMaker/scripts/mkntuplecfi.py for an illustration of how to use this class with the ROOT GUI classes.
Definition at line 24 of file Connection.h.
Constructor & Destructor Documentation
Connection::Connection (TQObject * sender, const char * signal, PyObject * receiver, const char * method)
Construct a signal/slott association.
Parameters
sender - The address of an object able to issue signals (e.g., a TGMainFrame)
signal - The function, typically of the sender, that is to be called when some action triggers it (e.g., ``CloseWindow()")
receiver - The address of the object that must respond to the signal
- The function, typically a method of the receiver, that is to be called upon the issuing of the associated signal.
Definition at line 16 of file Connection.cc.
References noArgs().
Connection::~Connection ()
Definition at line 32 of file Connection.cc.
References noArgs().
Member Function Documentation
const char* Connection::method () const inline
Definition at line 58 of file Connection.h.
References Slot::method().
Bool_t Connection::noArgs (std::string & signal)
True if signal has no arguments.
Definition at line 44 of file Connection.cc.
Referenced by Connection(), and ~Connection().
PyObject* Connection::receiver () const inline
Definition at line 55 of file Connection.h.
References Slot::receiver().
TQObject* Connection::sender () const inline
Definition at line 49 of file Connection.h.
const char* Connection::signal () const inline
Definition at line 52 of file Connection.h.
The documentation for this class was generated from the following files:
TBEventDisplay/interface/Connection.h
TBEventDisplay/src/Connection.cc