HGCal Test Beam: HGCalCondObjectContainerBase Class Reference
HGCalCondObjectContainerBase Class Reference
#include <HGCalCondObjectContainer.h>
Public Member Functions
HGCalCondObjectContainerBase (const HGCalCondObjectNumberingScheme *scheme, uint64_t ischeme)
HGCalCondObjectContainerBase ()
void setNumberingScheme (const HGCalCondObjectNumberingScheme *scheme)
void setNumberingScheme (const HGCalCondObjectNumberingScheme *scheme, uint64_t code)
const
HGCalCondObjectNumberingScheme * getNumberingScheme () const
uint64_t schemeCode () const
bool exists (DetId id) const
Protected Member Functions
size_t indexOf (DetId id) const
Detailed Description
Date:
Revision:
Author
J. Mans - Minnesota
Definition at line 27 of file HGCalCondObjectContainer.h.
Constructor & Destructor Documentation
HGCalCondObjectContainerBase::HGCalCondObjectContainerBase (const HGCalCondObjectNumberingScheme * scheme, uint64_t ischeme) inline
Definition at line 30 of file HGCalCondObjectContainer.h.
HGCalCondObjectContainerBase::HGCalCondObjectContainerBase () inline
Definition at line 31 of file HGCalCondObjectContainer.h.
Member Function Documentation
bool HGCalCondObjectContainerBase::exists (DetId id) const inline
Definition at line 51 of file HGCalCondObjectContainer.h.
References indexOf(), and HGCalCondObjectNumberingScheme::INVALID.
const HGCalCondObjectNumberingScheme* HGCalCondObjectContainerBase::getNumberingScheme () const inline
Definition at line 42 of file HGCalCondObjectContainer.h.
size_t HGCalCondObjectContainerBase::indexOf (DetId id) const protected
Definition at line 3 of file HGCalCondObjectContainer.cc.
References HGCalCondObjectNumberingScheme::denseIndexFor(), and HGCalCondObjectNumberingScheme::INVALID.
Referenced by exists(), HGCalCondObjectContainer< Payload >::get(), and HGCalCondObjectContainer< Payload >::set().
uint64_t HGCalCondObjectContainerBase::schemeCode () const inline
Definition at line 46 of file HGCalCondObjectContainer.h.
Referenced by HGCalCondObjectTextIO::store().
void HGCalCondObjectContainerBase::setNumberingScheme (const HGCalCondObjectNumberingScheme * scheme) inline
Definition at line 33 of file HGCalCondObjectContainer.h.
void HGCalCondObjectContainerBase::setNumberingScheme (const HGCalCondObjectNumberingScheme * scheme, uint64_t code) inline
Definition at line 37 of file HGCalCondObjectContainer.h.
The documentation for this class was generated from the following files:
CondObjects/interface/HGCalCondObjectContainer.h
CondObjects/src/HGCalCondObjectContainer.cc