HGCal Test Beam: HGCalDataFrameContainer< Digi > Class Template Reference
HGCalDataFrameContainer< Digi > Class Template Reference
#include <HGCalTBDataFrameContainers.h>
Public Types
typedef
edm::DataFrameContainer::size_type size_type
Public Member Functions
HGCalDataFrameContainer (int nsamples_per_digi=SKIROC::MAXSAMPLES, int isubdet=0)
void swap (DataFrameContainer &other)
Digi backDataFrame ()
int samples () const
void addDataFrame (DetId detid, const uint16_t *data)
void addDataFrame (DetId detid)
void push_back (const Digi &digi)
Detailed Description
template<class Digi>
class HGCalDataFrameContainer< Digi >
Definition at line 9 of file HGCalTBDataFrameContainers.h.
Member Typedef Documentation
template<class Digi > typedef edm::DataFrameContainer::size_type HGCalDataFrameContainer< Digi >::size_type
Definition at line 12 of file HGCalTBDataFrameContainers.h.
Constructor & Destructor Documentation
template<class Digi > HGCalDataFrameContainer< Digi >::HGCalDataFrameContainer (int nsamples_per_digi = SKIROC::MAXSAMPLES, int isubdet = 0) inline
Definition at line 14 of file HGCalTBDataFrameContainers.h.
Member Function Documentation
template<class Digi > void HGCalDataFrameContainer< Digi >::addDataFrame (DetId detid, const uint16_t * data) inline
Definition at line 31 of file HGCalTBDataFrameContainers.h.
References HGCalDataFrameContainer< Digi >::push_back().
template<class Digi > void HGCalDataFrameContainer< Digi >::addDataFrame (DetId detid) inline
Definition at line 35 of file HGCalTBDataFrameContainers.h.
References HGCalDataFrameContainer< Digi >::push_back().
template<class Digi > Digi HGCalDataFrameContainer< Digi >::backDataFrame () inline
Definition at line 23 of file HGCalTBDataFrameContainers.h.
template<class Digi > void HGCalDataFrameContainer< Digi >::push_back (const Digi & digi) inline
Definition at line 40 of file HGCalTBDataFrameContainers.h.
Referenced by HGCalDataFrameContainer< Digi >::addDataFrame().
template<class Digi > int HGCalDataFrameContainer< Digi >::samples () const inline
Definition at line 27 of file HGCalTBDataFrameContainers.h.
template<class Digi > void HGCalDataFrameContainer< Digi >::swap (DataFrameContainer & other) inline
Definition at line 16 of file HGCalTBDataFrameContainers.h.
The documentation for this class was generated from the following file:
DataFormats/interface/HGCalTBDataFrameContainers.h