HGCal Test Beam: SKIROC2DataFrame Class Reference
SKIROC2DataFrame Class Reference
#include <SKIROC2DataFrame.h>
Classes
class Sample
Public Member Functions
SKIROC2DataFrame ()
SKIROC2DataFrame (edm::DataFrame const &df)
void copyContent (const SKIROC2DataFrame &src)
HGCalTBDetId detid () const
Get the detector id.
edm::DataFrame::id_type id () const
edm::DataFrame::size_type size () const
more accessors
edm::DataFrame::iterator begin ()
iterators
edm::DataFrame::iterator end ()
edm::DataFrame::const_iterator begin () const
edm::DataFrame::const_iterator end () const
int samples () const
total number of samples in the digi
Sample operator[] (edm::DataFrame::size_type i) const
get the sample
void setSample (edm::DataFrame::size_type isample, int adc, int tdc)
set the sample contents
uint16_t flags () const
get the flag word
void setFlags (uint16_t v)
set the flag word
Static Public Attributes
static const int WORDS_PER_SAMPLE = 2
static const int HEADER_WORDS = 1
static const int FLAG_WORDS = 1
Detailed Description
Definition at line 8 of file SKIROC2DataFrame.h.
Constructor & Destructor Documentation
SKIROC2DataFrame::SKIROC2DataFrame () inline
Definition at line 16 of file SKIROC2DataFrame.h.
SKIROC2DataFrame::SKIROC2DataFrame (edm::DataFrame const & df) inline
Definition at line 17 of file SKIROC2DataFrame.h.
Member Function Documentation
edm::DataFrame::iterator SKIROC2DataFrame::begin () inline
iterators
Definition at line 57 of file SKIROC2DataFrame.h.
edm::DataFrame::const_iterator SKIROC2DataFrame::begin () const inline
Definition at line 65 of file SKIROC2DataFrame.h.
void SKIROC2DataFrame::copyContent (const SKIROC2DataFrame & src)
Definition at line 3 of file SKIROC2DataFrame.cc.
HGCalTBDetId SKIROC2DataFrame::detid () const inline
Get the detector id.
Definition at line 42 of file SKIROC2DataFrame.h.
Referenced by operator<<(), and HGCalTBRecHitProducer::produce().
edm::DataFrame::iterator SKIROC2DataFrame::end () inline
Definition at line 61 of file SKIROC2DataFrame.h.
edm::DataFrame::const_iterator SKIROC2DataFrame::end () const inline
Definition at line 69 of file SKIROC2DataFrame.h.
uint16_t SKIROC2DataFrame::flags () const inline
get the flag word
Definition at line 87 of file SKIROC2DataFrame.h.
References size().
edm::DataFrame::id_type SKIROC2DataFrame::id () const inline
Definition at line 47 of file SKIROC2DataFrame.h.
Sample SKIROC2DataFrame::operator[] (edm::DataFrame::size_type i) const inline
get the sample
Definition at line 80 of file SKIROC2DataFrame.h.
References HEADER_WORDS, and WORDS_PER_SAMPLE.
int SKIROC2DataFrame::samples () const inline
total number of samples in the digi
Definition at line 75 of file SKIROC2DataFrame.h.
References FLAG_WORDS, HEADER_WORDS, size(), and WORDS_PER_SAMPLE.
Referenced by operator<<(), and HGCalTBRecHitProducer::produce().
void SKIROC2DataFrame::setFlags (uint16_t v)
set the flag word
void SKIROC2DataFrame::setSample (edm::DataFrame::size_type isample, int adc, int tdc)
set the sample contents
Definition at line 7 of file SKIROC2DataFrame.cc.
References HEADER_WORDS, and WORDS_PER_SAMPLE.
edm::DataFrame::size_type SKIROC2DataFrame::size () const inline
more accessors
Definition at line 52 of file SKIROC2DataFrame.h.
Referenced by flags(), and samples().
Member Data Documentation
const int SKIROC2DataFrame::FLAG_WORDS = 1 static
Definition at line 14 of file SKIROC2DataFrame.h.
Referenced by samples().
const int SKIROC2DataFrame::HEADER_WORDS = 1 static
Definition at line 13 of file SKIROC2DataFrame.h.
Referenced by operator[](), samples(), and setSample().
const int SKIROC2DataFrame::WORDS_PER_SAMPLE = 2 static
Definition at line 12 of file SKIROC2DataFrame.h.
Referenced by operator[](), samples(), and setSample().
The documentation for this class was generated from the following files:
DataFormats/interface/SKIROC2DataFrame.h
DataFormats/src/SKIROC2DataFrame.cc