HGCal Test Beam: HGCalTBRawToDigi Class Reference
HGCalTBRawToDigi Class Reference
#include <HGCalTBRawToDigi.h>
Public Member Functions
HGCalTBRawToDigi (const edm::ParameterSet &ps)
virtual void produce (edm::Event &e, const edm::EventSetup &c)
virtual void beginJob ()
Detailed Description
Definition at line 25 of file HGCalTBRawToDigi.h.
Constructor & Destructor Documentation
HGCalTBRawToDigi::HGCalTBRawToDigi (const edm::ParameterSet & ps) explicit
Definition at line 7 of file HGCalTBRawToDigi.cc.
Member Function Documentation
void HGCalTBRawToDigi::beginJob () virtual
Todo:
this should be done by an ESProducer
Definition at line 16 of file HGCalTBRawToDigi.cc.
References HGCalCondObjectTextIO::load().
void HGCalTBRawToDigi::produce (edm::Event & e, const edm::EventSetup & c) virtual
Todo:
TDC value hardcoded to 0 because not in the readout
Definition at line 27 of file HGCalTBRawToDigi.cc.
References gray_to_binary(), and HGCalTBElectronicsId::rawId().
Member Data Documentation
HGCalElectronicsMap HGCalTBRawToDigi::emap_
Definition at line 37 of file HGCalTBRawToDigi.h.
The documentation for this class was generated from the following files:
RawToDigi/plugins/HGCalTBRawToDigi.h
RawToDigi/plugins/HGCalTBRawToDigi.cc