HGCal Test Beam: HGCalCondObjectContainer< Payload > Class Template Reference
HGCalCondObjectContainer< Payload > Class Template Reference
#include <HGCalCondObjectContainer.h>
Classes
struct Item
Public Member Functions
HGCalCondObjectContainer (const HGCalCondObjectNumberingScheme *scheme, uint64_t ischeme)
HGCalCondObjectContainer ()
const Item * get (DetId id) const
size_t size () const
const Item & get (size_t i) const
void set (DetId id, const Payload &value)
Public Member Functions inherited from HGCalCondObjectContainerBase
HGCalCondObjectContainerBase (const HGCalCondObjectNumberingScheme *scheme, uint64_t ischeme)
HGCalCondObjectContainerBase ()
void setNumberingScheme (const HGCalCondObjectNumberingScheme *scheme)
void setNumberingScheme (const HGCalCondObjectNumberingScheme *scheme, uint64_t code)
const
HGCalCondObjectNumberingScheme * getNumberingScheme () const
uint64_t schemeCode () const
bool exists (DetId id) const
Additional Inherited Members
Protected Member Functions inherited from HGCalCondObjectContainerBase
size_t indexOf (DetId id) const
Detailed Description
template<class Payload>
class HGCalCondObjectContainer< Payload >
Date:
Revision:
Author
J. Mans - Minnesota
Definition at line 69 of file HGCalCondObjectContainer.h.
Constructor & Destructor Documentation
template<class Payload> HGCalCondObjectContainer< Payload >::HGCalCondObjectContainer (const HGCalCondObjectNumberingScheme * scheme, uint64_t ischeme) inline
Definition at line 77 of file HGCalCondObjectContainer.h.
template<class Payload> HGCalCondObjectContainer< Payload >::HGCalCondObjectContainer () inline
Definition at line 80 of file HGCalCondObjectContainer.h.
Member Function Documentation
template<class Payload> const Item* HGCalCondObjectContainer< Payload >::get (DetId id) const inline
Definition at line 82 of file HGCalCondObjectContainer.h.
References HGCalCondObjectContainerBase::indexOf(), and HGCalCondObjectNumberingScheme::INVALID.
Referenced by HGCalTBRecHitProducer::produce(), and HGCalCondObjectTextIO::store().
template<class Payload> const Item& HGCalCondObjectContainer< Payload >::get (size_t i) const inline
Definition at line 91 of file HGCalCondObjectContainer.h.
template<class Payload> void HGCalCondObjectContainer< Payload >::set (DetId id, const Payload & value) inline
Definition at line 95 of file HGCalCondObjectContainer.h.
References HGCalCondObjectContainerBase::indexOf(), and HGCalCondObjectNumberingScheme::INVALID.
Referenced by HGCalCondObjectTextIO::load().
template<class Payload> size_t HGCalCondObjectContainer< Payload >::size () const inline
Definition at line 87 of file HGCalCondObjectContainer.h.
Referenced by HGCalTBRecHitProducer::produce(), and HGCalCondObjectTextIO::store().
The documentation for this class was generated from the following file:
CondObjects/interface/HGCalCondObjectContainer.h