HGCal Test Beam: HGCalCondObjectNumberingScheme Class Reference
HGCalCondObjectNumberingScheme Class Reference abstract
#include <HGCalCondObjectContainer.h>
Public Member Functions
virtual size_t rangeFor (uint64_t scheme) const =0
virtual size_t denseIndexFor (uint32_t rawDetId, uint64_t scheme) const =0
virtual size_t denseIndexFor (DetId rawDetId, uint64_t scheme) const
Static Public Attributes
static const size_t INVALID = (size_t) - 1
Detailed Description
Definition at line 8 of file HGCalCondObjectContainer.h.
Member Function Documentation
virtual size_t HGCalCondObjectNumberingScheme::denseIndexFor (uint32_t rawDetId, uint64_t scheme) const pure virtual
Implemented in HGCalTBNumberingScheme.
Referenced by denseIndexFor(), and HGCalCondObjectContainerBase::indexOf().
virtual size_t HGCalCondObjectNumberingScheme::denseIndexFor (DetId rawDetId, uint64_t scheme) const inline virtual
Definition at line 14 of file HGCalCondObjectContainer.h.
References denseIndexFor().
virtual size_t HGCalCondObjectNumberingScheme::rangeFor (uint64_t scheme) const pure virtual
Implemented in HGCalTBNumberingScheme.
Member Data Documentation
const size_t HGCalCondObjectNumberingScheme::INVALID = (size_t) - 1 static
Definition at line 11 of file HGCalCondObjectContainer.h.
Referenced by HGCalTBNumberingScheme::denseIndexFor(), HGCalCondObjectContainerBase::exists(), HGCalCondObjectContainer< Payload >::get(), HGCalCondObjectContainerBase::indexOf(), and HGCalCondObjectContainer< Payload >::set().
The documentation for this class was generated from the following file:
CondObjects/interface/HGCalCondObjectContainer.h