HGCal Test Beam: HGCalCondObjectTextIO Class Reference
HGCalCondObjectTextIO Class Reference
#include <HGCalCondObjectTextIO.h>
Public Member Functions
HGCalCondObjectTextIO (const HGCalCondObjectNumberingScheme *scheme)
bool load (const std::string &filename, HGCalCondObjectContainer< float > &)
load conditions from file
bool store (const std::string &filename, const HGCalCondObjectContainer< float > &)
saves condition to file
bool load (const std::string &filename, HGCalElectronicsMap &)
bool store (const std::string &filename, const HGCalElectronicsMap &)
Detailed Description
Date:
Revision:
Author
J. Mans - Minnesota
Todo:
load and store are HGCalCondObjectContainer not templated.... so now takes only floats!!!
Definition at line 16 of file HGCalCondObjectTextIO.h.
Constructor & Destructor Documentation
HGCalCondObjectTextIO::HGCalCondObjectTextIO (const HGCalCondObjectNumberingScheme * scheme) inline
Definition at line 19 of file HGCalCondObjectTextIO.h.
Member Function Documentation
bool HGCalCondObjectTextIO::load (const std::string & filename, HGCalCondObjectContainer< float > & cont)
load conditions from file
Definition at line 21 of file HGCalCondObjectTextIO.cc.
References HGCalCondObjectContainer< Payload >::set().
Referenced by HGCalTBRawToDigi::beginJob(), main(), and HGCalTBRecHitProducer::produce().
bool HGCalCondObjectTextIO::load (const std::string & filename, HGCalElectronicsMap & emap)
Definition at line 84 of file HGCalCondObjectTextIO.cc.
References HGCalElectronicsMap::insert(), and HGCalTBElectronicsId::rawId().
bool HGCalCondObjectTextIO::store (const std::string & filename, const HGCalCondObjectContainer< float > & cont)
saves condition to file
Definition at line 67 of file HGCalCondObjectTextIO.cc.
References HGCalCondObjectContainer< Payload >::get(), HGCalCondObjectContainerBase::schemeCode(), and HGCalCondObjectContainer< Payload >::size().
Referenced by main().
bool HGCalCondObjectTextIO::store (const std::string & filename, const HGCalElectronicsMap & emap)
Definition at line 119 of file HGCalCondObjectTextIO.cc.
References HGCalElectronicsMap::didAt(), HGCalElectronicsMap::eidAt(), and HGCalElectronicsMap::size().
The documentation for this class was generated from the following files:
CondObjects/interface/HGCalCondObjectTextIO.h
CondObjects/src/HGCalCondObjectTextIO.cc