HGCal Test Beam: HGCalTBRecHit Class Reference
HGCalTBRecHit Class Reference
#include <HGCalTBRecHit.h>
Public Types
enum Flags { kGood = 0, kHighGainSaturated, kLowGainSaturated }
typedef DetId key_type
Public Member Functions
enum HGCalTBRecHit::Flags HGCalTBRecHit ()
HGCalTBRecHit (const DetId &id, float energyLow, float energyHigh, float time, uint32_t flags=0)
HGCalTBDetId id () const
get the id
float energyLow ()
float energyHigh ()
void setFlag (int flag)
void unsetFlag (int flag)
bool checkFlag (int flag) const
Public Attributes
float _energyLow
float _energyHigh
Detailed Description
Author
Jeremy Mans
Todo:
fix the energy threshold for low gain saturation in a different way: now it's hardcoded
Definition at line 16 of file HGCalTBRecHit.h.
Member Typedef Documentation
typedef DetId HGCalTBRecHit::key_type
Definition at line 19 of file HGCalTBRecHit.h.
Member Enumeration Documentation
enum HGCalTBRecHit::Flags
Enumerator
kGood
kHighGainSaturated
kLowGainSaturated
Definition at line 21 of file HGCalTBRecHit.h.
Constructor & Destructor Documentation
HGCalTBRecHit::HGCalTBRecHit ()
Definition at line 5 of file HGCalTBRecHit.cc.
HGCalTBRecHit::HGCalTBRecHit (const DetId & id, float energyLow, float energyHigh, float time, uint32_t flags = 0)
Definition at line 10 of file HGCalTBRecHit.cc.
References checkFlag(), kHighGainSaturated, and kLowGainSaturated.
Member Function Documentation
bool HGCalTBRecHit::checkFlag (int flag) const inline
Definition at line 54 of file HGCalTBRecHit.h.
Referenced by HGCalTBRecHit().
float HGCalTBRecHit::energyHigh () inline
Definition at line 44 of file HGCalTBRecHit.h.
References _energyHigh.
float HGCalTBRecHit::energyLow () inline
Definition at line 39 of file HGCalTBRecHit.h.
References _energyLow.
HGCalTBDetId HGCalTBRecHit::id () const inline
get the id
Definition at line 32 of file HGCalTBRecHit.h.
Referenced by operator<<().
void HGCalTBRecHit::setFlag (int flag) inline
Definition at line 50 of file HGCalTBRecHit.h.
Referenced by HGCalTBRecHitProducer::produce().
void HGCalTBRecHit::unsetFlag (int flag) inline
Definition at line 51 of file HGCalTBRecHit.h.
Member Data Documentation
float HGCalTBRecHit::_energyHigh
Definition at line 37 of file HGCalTBRecHit.h.
Referenced by energyHigh().
float HGCalTBRecHit::_energyLow
Definition at line 37 of file HGCalTBRecHit.h.
Referenced by energyLow().
The documentation for this class was generated from the following files:
DataFormats/interface/HGCalTBRecHit.h
DataFormats/src/HGCalTBRecHit.cc