/control/verbose 0
/control/saveHistory 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/N03/det/setField 0.0 T
/N03/det/setModel 5
/random/setSeeds 66374 94920
/gun/particle 	 e-
/gun/direction	 0 0 1
/gun/energy	 32 GeV
/gun/position	 0 0 -2 cm

# some visualization

/vis/scene/create

# open VRML file
/vis/open VRML2FILE

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 40. 60.

# Specify style (surface or wireframe):
/vis/viewer/set/style wireframe

/vis/viewer/zoom 20

# Draw coordinate axes (50cm long)
/vis/scene/add/axes 0 0 0 50 cm

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma red
/vis/modeling/trajectories/drawByParticleID-0/set pi+ green
/vis/modeling/trajectories/drawByParticleID-0/set pi- green
/vis/modeling/trajectories/drawByParticleID-0/set mu+ cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- cyan

# Draw smooth trajectories
/vis/scene/add/trajectories smooth

# run 2 events
/run/beamOn 2